### ISSUE TITLE
Search and display over all test-results

### ISSUE THREAD

**Issue by wmanley** [wmanley/stb-tester-service#33]
In #25 we are planning on reaching feature-parity with the current results view, but not much more.  Most notably this doesn't include performance improvements to support >5000 results while still being fast.

This ticket can be used to track the work that we've done and the tasks that are still to do.

- [ ] Store results in database #4
- [ ] Link to results of a job 
- [ ] Searching results on the server-side #32
- [ ] Feature parity with `stbt batch` #25
- [ ] A public API for retrieving results per job
- [ ] Search across results categories
- [ ] Display >100000 results

Nice to have:

- [ ] Animate the details pane sliding open/shut.
- [ ] Button to hide details pane again.
- [ ] Button to make details pane full screen.
- [ ] Search in the exception backtrace.
- [ ] Fixed position for top navbar across the app.
- [ ] Fixed position for searchbar above the table of results.
- [ ] "Filter like this one" button in details pane for job id etc.
- [ ] Pressing "back" from a logfile/image should remember your position.
